name: Fortress.org 

on:
  push:
    branches:
      - master

  Fortress.org 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g firebase-tools
      - run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
